const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const state={user:JSON.parse(localStorage.getItem('aiplay_user_v2')||'null'),rep:+localStorage.getItem('aiplay_rep_v2')||0,items:JSON.parse(localStorage.getItem('aiplay_items_v2')||'[]'),following:JSON.parse(localStorage.getItem('aiplay_following_v2')||'[]')};
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function save(){localStorage.setItem('aiplay_user_v2',JSON.stringify(state.user));localStorage.setItem('aiplay_rep_v2',state.rep);localStorage.setItem('aiplay_items_v2',JSON.stringify(state.items));localStorage.setItem('aiplay_following_v2',JSON.stringify(state.following))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2400)}
function openModal(id){$('#'+id)?.classList.add('open')} function closeModal(id){$('#'+id)?.classList.remove('open')}
function ensure(action){if(!state.user){switchAuth('signup');openModal('authModal');toast('כדי '+action+' צריך לפתוח חשבון');return false}return true}
function currentLevel(){return state.rep>=2500?5:state.rep>=1000?4:state.rep>=500?3:state.rep>=100?2:1}
function renderUser(){const logged=!!state.user;$('#loginOpen').classList.toggle('hidden',logged);$('#signupOpen').classList.toggle('hidden',logged);$('#profileOpen').classList.toggle('hidden',!logged);$('#navUser').textContent=state.user?.name||'אורח';$('#navAvatar').textContent=(state.user?.name||'א').charAt(0);$('#navRep').textContent=state.rep+' ✦';$('#repValue').textContent=state.rep;$('#repLevel').textContent=currentLevel();$('#myCount').textContent=state.items.length;const lv=currentLevel(),target=lv===1?100:lv===2?500:lv===3?1000:lv===4?2500:5000,prev=lv===1?0:lv===2?100:lv===3?500:lv===4?1000:2500;$('#repTarget').textContent='יעד: '+target+' ✦';$('#repGoal').textContent=logged?(state.rep>=target?'הגעתם ליעד הרמה':'עוד '+Math.max(0,target-state.rep)+' ✦ ליעד'):'פתחו חשבון כדי להתחיל';$('#repProgress').style.width=(state.rep<=prev?0:Math.min(100,(state.rep-prev)/(target-prev)*100))+'%' }
function allItems(){return Array.isArray(state.items)?state.items:[]}
function renderFeed(filter='all',query=''){let arr=allItems().filter(x=>(filter==='all'||filter==='new'||x.type===filter)&&((x.title||'')+' '+(x.author||'')).toLowerCase().includes(query.toLowerCase()));if(filter==='new')arr=arr.slice().reverse();$('#feedGrid').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty"><strong>אין עדיין תוכן אמיתי להצגה</strong><span>הפיד אינו מכיל נתוני דמה. העלה יצירה או חבר את האתר לשרת תוכן כדי להציג פריטים אמיתיים.</span></div>';bindCards()}
function renderDiscover(q=''){let arr=allItems().filter(x=>((x.title||'')+' '+(x.author||'')).toLowerCase().includes(q.toLowerCase()));$('#discoverGrid').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty"><strong>לא נמצאו יצירות</strong><span>החיפוש עובד רק מול הנתונים הקיימים בפלטפורמה כרגע.</span></div>';bindCards()}
function card(x){const video=x.type==='video';return '<article class="content-card"><div class="thumb '+esc(x.thumb||'')+'">'+(video?'<span class="play">▶</span>':'')+'<span class="kind">'+(video?'VIDEO':'IMAGE')+'</span></div><div class="content-body"><h3>'+esc(x.title||'ללא שם')+'</h3><div class="meta-row"><span class="author-dot">'+esc(x.initial||(x.author||'א').charAt(0))+'</span><span>'+esc(x.author||'לא ידוע')+'</span></div><div class="card-actions"><button class="tiny watch" data-id="'+esc(x.id)+'">▶ פתיחה</button><button class="tiny primary download" data-id="'+esc(x.id)+'">↓ הורדה</button></div></div></article>'}
function bindCards(){$$('.watch').forEach(b=>b.onclick=()=>toast('הפתיחה תתחבר לנגן האמיתי לאחר חיבור שרת התוכן'));$$('.download').forEach(b=>b.onclick=()=>{if(!ensure('להוריד'))return;if(state.rep<100){toast('הורדות ייפתחו מרמה של 100 ✦');return}toast('הורדה תבוצע דרך שרת הקבצים לאחר חיבור Backend')})}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.page===name));$$('.side-link[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===name));if(name==='home')renderFeed();if(name==='discover')renderDiscover();if(name==='leaderboard')renderUser();if(name==='profile'){switchAuth(state.user?'login':'signup');openModal('authModal')}}
function switchAuth(mode){$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.auth===mode));$$('.signup-field').forEach(x=>x.classList.toggle('hidden',mode!=='signup'));$('#authTitle').textContent=mode==='signup'?'פותחים חשבון':'ברוכים הבאים';$('#authSub').textContent=mode==='signup'?'יוצרים ומשתפים.':'כניסה לחשבון המקומי.';$('#authSubmit').textContent=mode==='signup'?'פתיחת חשבון':'כניסה'}
$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});
$$('.side-link[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();switchView(a.dataset.view)});$$('.mobile-nav [data-view]').forEach(a=>a.onclick=()=>switchView(a.dataset.view));
$('#loginOpen').onclick=()=>{switchAuth('login');openModal('authModal')};$('#signupOpen').onclick=()=>{switchAuth('signup');openModal('authModal')};$('#profileOpen').onclick=()=>{switchAuth('login');openModal('authModal')};
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#heroCreate').onclick=()=>{if(ensure('ליצור'))openModal('studioModal')};$('#mobileCreate').onclick=()=>{if(ensure('ליצור'))openModal('studioModal')};$('#heroUpload').onclick=()=>{if(ensure('להעלות'))openModal('uploadModal')};$('#studioOpen').onclick=()=>{if(ensure('ליצור'))openModal('studioModal')};
$$('.chips button').forEach(b=>b.onclick=()=>{$$('.chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderFeed(b.dataset.filter)});
$('#authSubmit').onclick=()=>{const signup=$('.tabs button.active').dataset.auth==='signup',name=$('#authName').value.trim(),email=$('#authEmail').value.trim(),pass=$('#authPass').value,terms=$('#termsOk').checked;if(!email.includes('@')||pass.length<4||(signup&&(!name||!terms))){toast('בדקו את הפרטים');return}state.user={name:signup?name:email.split('@')[0],email,verified:false};if(signup)state.rep=Math.max(state.rep,5);save();closeModal('authModal');renderUser();toast('החשבון נשמר מקומית בלבד')};
$$('.tabs button').forEach(b=>b.onclick=()=>switchAuth(b.dataset.auth));
$$('.studio-tabs button').forEach(b=>b.onclick=()=>{$$('.studio-tabs button').forEach(x=>x.classList.toggle('active',x===b))});
$('#createWork').onclick=()=>{if(!ensure('ליצור'))return;const p=$('#prompt').value.trim();if(!p){toast('כתבו פרומפט');return}const type=$('.studio-tabs button.active').dataset.studioType==='image'?'image':'video';state.items.unshift({id:'c'+Date.now(),type,title:p.slice(0,60),author:state.user.name,initial:state.user.name.charAt(0),thumb:'local',views:0,status:'review',time:'עכשיו'});state.rep+=2;save();renderFeed();renderDiscover();renderUser();closeModal('studioModal');$('#prompt').value='';toast('נשמרה טיוטה מקומית. אין עדיין פרסום שרת אמיתי')};
$('#file').onchange=e=>{const f=e.target.files[0];if(f)$('#fileName').textContent=f.name};
$('#uploadSubmit').onclick=()=>{if(!ensure('להעלות'))return;const f=$('#file').files[0],title=$('#uploadTitle').value.trim();if(!f||!title){toast('בחרו קובץ ושם');return}state.items.unshift({id:'u'+Date.now(),type:f.type.startsWith('video')?'video':'image',title,author:state.user.name,initial:state.user.name.charAt(0),thumb:'local',views:0,status:'review',time:'עכשיו'});state.rep+=1;save();renderFeed();renderDiscover();renderUser();closeModal('uploadModal');toast('הפריט נשמר מקומית בלבד')};
$('#searchOpen').onclick=()=>{openModal('searchModal');$('#searchInput').focus();search('')};$('#searchInput').oninput=e=>search(e.target.value);function search(q){const arr=allItems().filter(x=>((x.title||'')+' '+(x.author||'')).toLowerCase().includes((q||'').toLowerCase()));$('#searchResults').innerHTML=arr.length?arr.slice(0,12).map(x=>'<div class="search-result"><b>'+esc(x.title)+'</b><small>'+esc(x.author)+'</small></div>').join(''):'<div class="search-result"><small>אין תוצאות אמיתיות כרגע.</small></div>'}
$('#topSearch').oninput=e=>{switchView('discover');$('#discoverSearch').value=e.target.value;renderDiscover(e.target.value)};$('#discoverSearch').oninput=e=>renderDiscover(e.target.value);$('#discoverSearchBtn').onclick=()=>renderDiscover($('#discoverSearch').value);
renderFeed();renderDiscover();renderUser();