const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const state={user:JSON.parse(localStorage.getItem('aiplay_user_v2')||'null'),rep:+localStorage.getItem('aiplay_rep_v2')||0,items:JSON.parse(localStorage.getItem('aiplay_items_v2')||'[]'),following:JSON.parse(localStorage.getItem('aiplay_following_v2')||'[]')};
const base=[
{id:1,type:'video',title:'עיר של מחר',author:'דניאל סטודיו',initial:'ד',views:18421,thumb:'a',time:'לפני 12 דק׳'},
{id:2,type:'image',title:'היער שמעבר לעננים',author:'נועם קריאייטיב',initial:'נ',views:12690,thumb:'b',time:'לפני 28 דק׳'},
{id:3,type:'video',title:'מסע קטן אל האור',author:'אלעד AI',initial:'ע',views:8910,thumb:'c',time:'לפני 41 דק׳'},
{id:4,type:'image',title:'הנסיך מהעיר הכחולה',author:'יצחק סטודיו',initial:'י',views:7410,thumb:'d',time:'לפני שעה'},
{id:5,type:'video',title:'שקט במדבר',author:'יוצר_84',initial:'י',views:5210,thumb:'e',time:'לפני שעתיים'},
{id:6,type:'image',title:'חלון לעולם אחר',author:'מיכאל יוצר',initial:'מ',views:4430,thumb:'f',time:'לפני 3 שעות'}];
const creators=[['דניאל סטודיו','2,840','ד'],['נועם קריאייטיב','2,160','נ'],['אלעד AI','1,890','ע'],['יצחק סטודיו','1,430','י']];
const leaders=[['דניאל סטודיו','14,842','ד'],['נועם קריאייטיב','11,460','נ'],['אלעד AI','9,190','ע'],['יצחק סטודיו','7,520','י'],['יוצר_84','6,980','י']];
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function save(){localStorage.setItem('aiplay_user_v2',JSON.stringify(state.user));localStorage.setItem('aiplay_rep_v2',state.rep);localStorage.setItem('aiplay_items_v2',JSON.stringify(state.items));localStorage.setItem('aiplay_following_v2',JSON.stringify(state.following))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2600)}
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}
function ensure(action){if(!state.user){switchAuth('signup');openModal('authModal');toast('כדי '+action+' צריך לפתוח חשבון');return false}return true}
function currentLevel(){return state.rep>=2500?5:state.rep>=1000?4:state.rep>=500?3:state.rep>=100?2:1}
function renderUser(){const logged=!!state.user;$('#loginOpen').classList.toggle('hidden',logged);$('#signupOpen').classList.toggle('hidden',logged);$('#profileOpen').classList.toggle('hidden',!logged);$('#navUser').textContent=state.user?.name||'אורח';$('#navAvatar').textContent=(state.user?.name||'א').charAt(0);$('#navRep').textContent=state.rep+' ✦';$('#repValue').textContent=state.rep;const lv=currentLevel();$('#repLevel').textContent=lv;const target=lv===1?100:lv===2?500:lv===3?1000:lv===4?2500:5000;const prev=lv===1?0:lv===2?100:lv===3?500:lv===4?1000:2500;$('#repProgress').style.width=Math.max(3,Math.min(100,(state.rep-prev)/(target-prev)*100))+'%';$('#repTarget').textContent=target+' ✦';$('#repGoal').textContent=logged?(state.rep>=target?'הגעתם לרמה הבאה!':'עוד '+Math.max(0,target-state.rep)+' ✦ לרמה הבאה'):'פתחו חשבון כדי להתחיל'}
function allItems(){return state.items.concat(base)}
function renderFeed(filter,query){filter=filter||'all';query=query||'';let arr=allItems().filter(x=>(filter==='all'||filter==='new'||x.type===filter)&&((x.title+' '+x.author).toLowerCase().includes(query.toLowerCase())));if(filter==='new')arr=arr.slice(0,6);$('#feedGrid').innerHTML=arr.map(function(x){return '<article class="content-card"><div class="thumb '+(x.thumb||'a')+'">'+(x.type==='video'?'<span class="play">▶</span>':'')+'<span class="kind">'+(x.type==='video'?'VIDEO':'IMAGE')+'</span></div><div class="content-body"><h3>'+esc(x.title)+'</h3><div class="meta-row"><div class="author-row"><span class="author-dot">'+esc(x.initial)+'</span><span>'+esc(x.author)+'</span></div><span>◉ '+Number(x.views||0).toLocaleString('he-IL')+' · '+esc(x.time||'עכשיו')+'</span></div><div class="card-actions"><button class="tiny watch" data-id="'+x.id+'">▶ צפייה</button><button class="tiny primary download" data-id="'+x.id+'">↓ הורדה</button></div></div></article>'}).join('')||'<div class="panel">לא נמצאו תוצאות.</div>';bindCards()}
function bindCards(){$$('.watch').forEach(function(b){b.onclick=function(){toast('הצפייה התחילה · היוצר מקבל מוניטין על פעילות איכותית')}});$$('.download').forEach(function(b){b.onclick=function(){if(!ensure('להוריד יצירה'))return;if(state.rep<100){toast('הורדות נפתחות החל מ־100 ✦ מוניטין');return}toast('הורדה אושרה · ב־Production הפעולה תירשם בצד השרת')}})}
function renderCreators(){$('#creatorGrid').innerHTML=creators.map(function(c){return '<div class="creator"><div class="creator-avatar">'+c[2]+'</div><h3>'+c[0]+'</h3><p>יוצר תוכן AI · פעיל היום</p><span class="rep-chip">✦ '+c[1]+' מוניטין</span><button class="follow-btn" data-name="'+esc(c[0])+'">'+(state.following.includes(c[0])?'✓ במעקב':'＋ עקוב')+'</button></div>'}).join('');$$('.follow-btn').forEach(function(b){b.onclick=function(){if(!ensure('לעקוב אחרי יוצרים'))return;const n=b.dataset.name;state.following=state.following.includes(n)?state.following.filter(x=>x!==n):state.following.concat(n);save();renderCreators();toast(state.following.includes(n)?'היוצר נוסף למעקב':'המעקב הוסר')}})}
function renderLeaders(){$('#leaderList').innerHTML=leaders.map(function(l,i){return '<div class="leader-row"><span>0'+(i+1)+'</span><div class="leader-user"><span class="leader-avatar">'+l[2]+'</span><div><strong>'+l[0]+'</strong><small>'+(i===0?'מוביל השבוע':'יוצר פעיל')+'</small></div></div><span class="leader-score">✦ '+l[1]+'</span></div>'}).join('')}
function switchAuth(mode){$$('.tabs button').forEach(function(x){x.classList.toggle('active',x.dataset.auth===mode)});$$('.signup-field').forEach(function(x){x.classList.toggle('hidden',mode!=='signup')});$('#authTitle').textContent=mode==='signup'?'פותחים חשבון':'ברוכים הבאים חזרה';$('#authSub').textContent=mode==='signup'?'יוצרים, משתפים ובונים מוניטין.':'חזרו ליוצרים וליצירות שלכם.';$('#authSubmit').textContent=mode==='signup'?'פתיחת חשבון':'כניסה'}
$$('[data-close]').forEach(function(b){b.onclick=function(){closeModal(b.dataset.close)}});$$('.modal').forEach(function(m){m.onclick=function(e){if(e.target===m)m.classList.remove('open')}});
$('#loginOpen').onclick=function(){switchAuth('login');openModal('authModal')};$('#signupOpen').onclick=function(){switchAuth('signup');openModal('authModal')};
$('#heroCreate').onclick=function(){if(ensure('ליצור'))openModal('studioModal')};$('#heroUpload').onclick=function(){if(ensure('להעלות יצירה'))openModal('uploadModal')};$('#studioOpen').onclick=function(){if(ensure('לפתוח את הסטודיו'))openModal('studioModal')};$('#missionBtn').onclick=function(){if(ensure('ליצור'))openModal('studioModal')};$('#bottomSignup').onclick=function(){switchAuth('signup');openModal('authModal')};$('#repInfo').onclick=function(){toast('ב־Production המוניטין יחושב בצד השרת לפי צפיות, יצירות מאושרות והורדות אמיתיות')};
$$('.tabs button').forEach(function(b){b.onclick=function(){switchAuth(b.dataset.auth)}});
$('#authSubmit').onclick=function(){const signup=$('.tabs button.active').dataset.auth==='signup',name=$('#authName').value.trim(),email=$('#authEmail').value.trim(),pass=$('#authPass').value,terms=$('#termsOk').checked;if(!email||!email.includes('@')||pass.length<4||(signup&&!name)||(signup&&!terms)){toast('בדקו את הפרטים וסמנו הסכמה לתנאים');return}state.user={name:signup?name:email.split('@')[0],email:email,verified:false};if(signup)state.rep=Math.max(state.rep,5);save();closeModal('authModal');renderUser();toast(signup?'החשבון נפתח. מסך אימות המייל מוכן לחיבור שרת.':'נכנסתם בהצלחה')};
$$('.studio-tabs button').forEach(function(b){b.onclick=function(){$$('.studio-tabs button').forEach(function(x){x.classList.toggle('active',x===b)})}});
$('#createWork').onclick=function(){if(!ensure('ליצור'))return;const p=$('#prompt').value.trim();if(!p){toast('כתבו קודם רעיון ליצירה');return}const kind=document.querySelector('.studio-tabs button.active').dataset.studioType==='image'?'image':'video';state.items.unshift({id:'c'+Date.now(),type:kind,title:p.slice(0,36)+(p.length>36?'…':''),author:state.user.name,initial:state.user.name.charAt(0),views:0,thumb:'e',time:'עכשיו',status:'review'});state.rep+=2;save();renderFeed();renderUser();closeModal('studioModal');$('#prompt').value='';toast('הטיוטה נשלחה לבדיקה ידנית · +2 מוניטין')};
$('#file').onchange=function(e){const f=e.target.files[0];if(f)$('#fileName').textContent=f.name};
$('#uploadSubmit').onclick=function(){if(!ensure('להעלות'))return;const f=$('#file').files[0],title=$('#uploadTitle').value.trim();if(!f||!title){toast('בחרו קובץ והוסיפו שם');return}state.items.unshift({id:'u'+Date.now(),type:f.type.startsWith('video')?'video':'image',title:title,author:state.user.name,initial:state.user.name.charAt(0),views:0,thumb:'f',time:'עכשיו',status:'review'});state.rep+=1;save();renderFeed();renderUser();closeModal('uploadModal');toast('הקובץ עלה לתור הבדיקה · +1 מוניטין')};
$('#searchOpen').onclick=function(){openModal('searchModal');$('#searchInput').focus()};function search(q){const arr=allItems().filter(x=>!q||((x.title+' '+x.author).toLowerCase().includes(q.toLowerCase())));$('#searchResults').innerHTML=arr.slice(0,8).map(x=>'<div class="search-result"><b>'+esc(x.title)+'</b><small>'+esc(x.author)+' · '+Number(x.views||0).toLocaleString('he-IL')+' צפיות</small></div>').join('')||'<div class="search-result"><small>לא נמצאו תוצאות.</small></div>'}$('#searchInput').oninput=function(e){search(e.target.value)};$$('.search-hints button').forEach(function(b){b.onclick=function(){$('#searchInput').value=b.textContent;search(b.textContent)}});
$('.pills button').forEach(function(b){b.onclick=function(){$$('.filter-pills button').forEach(function(x){x.classList.remove('active')});b.classList.add('active');renderFeed(b.dataset.filter)}});
$('#profileOpen').onclick=function(){toast('פרופיל מלא יתחבר ל־Auth אמיתי בשלב השרת')};
renderFeed();renderCreators();renderLeaders();renderUser();search('');
